add prometheus server
hopkings2008/yigfs pull request #96
Opened 2022-09-16 10:25 UTC by duanjh7

Signed-off-by: duanjh7 <18204311659@163.com>

2022-09-16 10:35 UTC, hopkings2008 requested changes
please save the fsid into BlockHeader

2022-09-16 10:35 UTC, hopkings2008 commented on data_server/access/proto/access.proto
> +	string fsid = 2;
please add fsid into BlockHeader

2022-09-16 10:35 UTC, hopkings2008 commented on data_server/backend/src/input_stream.rs
> +                                .update_write_total_bytes(data.fsid, data.data.len() as u64);
fsid should not in data either

2022-09-19 01:48 UTC, duanjh7 commented on data_server/access/proto/access.proto
> +	string fsid = 2;
已修改

2022-09-19 01:48 UTC, duanjh7 commented on data_server/backend/src/input_stream.rs
> +                                .update_write_total_bytes(data.fsid, data.data.len() as u64);
已修改

2022-09-20 09:06 UTC, merged